#!/usr/bin/env python3
"""Regenerate FEATURE_PARITY.md's Phase-2C Packet Evidence table from live artifacts.

Per br-frankenpandas-albra (fd90.153): the static table in
FEATURE_PARITY.md fell out of date as the workspace grew from ~21
parity-green checkpoints to 430 distinct packet suites. This script
walks `artifacts/phase2c/FP-P2[CD]-NNN/parity_gate_result.json` and
emits an aggregate summary plus a compact per-packet status block.

Usage:
    python3 scripts/gen_feature_parity_table.py
    python3 scripts/gen_feature_parity_table.py --check    # exits 1 if FEATURE_PARITY.md is stale
    python3 scripts/gen_feature_parity_table.py --out custom/path.md

The generated block lives between two HTML comment markers in
FEATURE_PARITY.md:
    <!-- BEGIN AUTO-PACKET-TABLE -->
    ... auto-generated content ...
    <!-- END AUTO-PACKET-TABLE -->

Outside those markers, the file is untouched.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Iterable

REPO_ROOT = Path(__file__).resolve().parent.parent
PHASE2C_DIR = REPO_ROOT / "artifacts" / "phase2c"
TARGET_FILE = REPO_ROOT / "FEATURE_PARITY.md"

BEGIN_MARKER = "<!-- BEGIN AUTO-PACKET-TABLE -->"
END_MARKER = "<!-- END AUTO-PACKET-TABLE -->"

PACKET_DIR_RE = re.compile(r"^FP-P2[CD]-\d+$")


def load_packet_results(phase2c_dir: Path) -> list[dict]:
    """Walk artifacts/phase2c/FP-P2[CD]-NNN/ and load parity_gate_result.json."""
    results: list[dict] = []
    if not phase2c_dir.is_dir():
        return results
    for entry in sorted(phase2c_dir.iterdir()):
        if not entry.is_dir() or not PACKET_DIR_RE.match(entry.name):
            continue
        gate = entry / "parity_gate_result.json"
        if not gate.is_file():
            # Packet dir present but no gate yet — record as pending.
            results.append(
                {"packet_id": entry.name, "pass": None, "fixture_count": 0}
            )
            continue
        try:
            data = json.loads(gate.read_text())
        except json.JSONDecodeError as e:
            print(f"warning: {gate} unparseable: {e}", file=sys.stderr)
            continue
        results.append(data)
    return results


def render_block(results: list[dict]) -> str:
    """Render the auto-generated table between BEGIN/END markers."""
    total = len(results)
    passed = sum(1 for r in results if r.get("pass") is True)
    failed = sum(1 for r in results if r.get("pass") is False)
    pending = sum(1 for r in results if r.get("pass") is None)

    p2c = [r for r in results if r["packet_id"].startswith("FP-P2C-")]
    p2d = [r for r in results if r["packet_id"].startswith("FP-P2D-")]

    lines = [
        BEGIN_MARKER,
        f"<!-- Auto-generated by scripts/gen_feature_parity_table.py — do not edit by hand. -->",
        "",
        "> **What `pass` means here:** the `pass` boolean inside",
        "> `parity_gate_result.json` reflects the per-packet **gate threshold**",
        "> (typically: 0 fixture failures required). It is a stricter signal",
        "> than the lib-level `cargo test -p fp-conformance --lib` pass count",
        "> (~557/562 = 99% as of the README's Testing section), which counts",
        "> individual `#[test]` functions returning `Ok`. A packet can have",
        "> hundreds of green lib tests but still report `pass: false` here if",
        "> any single fixture inside it tripped the per-packet gate. Read",
        "> aggregate counts below as gate-level, not lib-test-level.",
        "",
        "**Aggregate status (live from `artifacts/phase2c/`):**",
        "",
        f"- Total packet suites: **{total}**",
        f"- Gate passing: **{passed}** ({passed * 100 // total if total else 0}%)",
        f"- Gate failing: **{failed}**",
        f"- Pending (no gate result yet): **{pending}**",
        "",
        f"By family: FP-P2C **{len(p2c)}** ({sum(1 for r in p2c if r.get('pass') is True)} gate-passing) · "
        f"FP-P2D **{len(p2d)}** ({sum(1 for r in p2d if r.get('pass') is True)} gate-passing)",
        "",
        "**Compact status by packet** (✓ gate-pass / ✗ gate-fail / · pending):",
        "",
    ]

    def emit_compact(family_results: list[dict], width: int = 6) -> None:
        rows = []
        for i, r in enumerate(family_results):
            pid = r["packet_id"]
            mark = (
                "✓" if r.get("pass") is True else "✗" if r.get("pass") is False else "·"
            )
            rows.append(f"{pid} {mark}")
        # Render in a column grid for compactness
        for chunk_start in range(0, len(rows), width):
            line = "  ".join(f"`{cell}`" for cell in rows[chunk_start : chunk_start + width])
            lines.append(line + "  ")

    if p2c:
        lines.append("**FP-P2C (Series-level):**")
        lines.append("")
        emit_compact(p2c)
        lines.append("")
    if p2d:
        lines.append("**FP-P2D (DataFrame-level):**")
        lines.append("")
        emit_compact(p2d)
        lines.append("")

    failing = [r for r in results if r.get("pass") is False]
    if failing:
        # When there are many failing packets, show only the first N to keep the
        # block compact. The full ledger lives in artifacts/phase2c/drift_history.jsonl.
        FAILING_HEAD_LIMIT = 25
        head = failing[:FAILING_HEAD_LIMIT]
        suppressed = len(failing) - len(head)
        lines.append(
            f"**Failing packets (showing first {len(head)} of {len(failing)}):**"
        )
        lines.append("")
        lines.append("| Packet | First reason |")
        lines.append("|---|---|")
        for r in head:
            reasons = r.get("reasons") or []
            first = reasons[0] if reasons else "(no reason recorded)"
            # Escape pipe chars to avoid breaking the table
            first = str(first).replace("|", "\\|")
            if len(first) > 120:
                first = first[:117] + "..."
            lines.append(f"| `{r['packet_id']}` | {first} |")
        if suppressed > 0:
            lines.append(
                f"| ... | _and {suppressed} more — see `artifacts/phase2c/drift_history.jsonl`_ |"
            )
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


def patch_target(target: Path, block: str) -> str:
    """Replace the BEGIN/END block in `target` with `block`. Insert if absent."""
    text = target.read_text() if target.exists() else ""
    if BEGIN_MARKER in text and END_MARKER in text:
        prefix = text.split(BEGIN_MARKER, 1)[0]
        suffix = text.split(END_MARKER, 1)[1]
        return prefix.rstrip("\n") + "\n\n" + block + "\n" + suffix.lstrip("\n")
    # Append to end if no markers yet.
    sep = "\n\n" if text and not text.endswith("\n\n") else ""
    return text + sep + block + "\n"


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if FEATURE_PARITY.md is stale (does not match what we'd write).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=TARGET_FILE,
        help="Output path (default: FEATURE_PARITY.md)",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    results = load_packet_results(PHASE2C_DIR)
    if not results:
        print(
            f"error: no packet results found under {PHASE2C_DIR}",
            file=sys.stderr,
        )
        return 1

    block = render_block(results)
    new_text = patch_target(args.out, block)

    if args.check:
        existing = args.out.read_text() if args.out.exists() else ""
        if existing != new_text:
            print(
                f"FEATURE_PARITY.md is stale; run "
                f"`python3 scripts/gen_feature_parity_table.py` to refresh.",
                file=sys.stderr,
            )
            return 1
        print(f"{args.out.name} is up to date ({len(results)} packets).")
        return 0

    args.out.write_text(new_text)
    print(
        f"wrote {len(results)} packet rows to {args.out.name} "
        f"({sum(1 for r in results if r.get('pass') is True)} passing)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
