#!/usr/bin/env python3
"""Regenerate conformance fixtures against the current pandas oracle.

br-frankenpandas-fixture-corpus-stale-vs-oracle-p6srr step 1: the entry point
that bead says does not exist. Everything else it asks for (regenerate, review
the diff, document divergences) depends on having this.

WHAT IT DOES
    For each fixture, pipe the fixture itself to `pandas_oracle.py` — which is
    exactly what the Rust harness does (`serde_json::to_vec(fixture)` in
    crates/fp-conformance/src/lib.rs) — and compare the returned `expected_*`
    blocks and provenance against what is on disk.

DRY RUN IS THE DEFAULT, ON PURPOSE.
    AGENTS.md names the "golden regeneration reflex" as a forbidden pattern, and
    p6srr explicitly warns that making this gate green without review destroys
    the only evidence it was checking. So the default prints a report and writes
    NOTHING; `--apply` is required to touch the corpus, and it refuses unless
    you have also passed `--i-reviewed-the-diff`.

THE REPORT SEPARATES TWO VERY DIFFERENT OUTCOMES
    provenance-only : the oracle produces byte-identical expected values; only
                      the recorded sha/timestamp were stale. Low risk.
    VALUE MOVED     : an expected value actually changed. Every one of these
                      needs a human reading, because per p6srr it is either a
                      real oracle fix, a regression, or an artefact of this
                      fixture having been generated by a much older oracle than
                      its neighbours. Values are bucketed by their PRIOR oracle
                      sha so the 11 generations in the corpus can be reviewed
                      separately.

Only keys the fixture ALREADY HAS are updated. The oracle response carries every
`expected_*` block (mostly null); copying them wholesale would bloat all 1258
fixtures with nulls and destroy the diff's meaning.
"""
from __future__ import annotations

import argparse
import collections
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ORACLE = PROJECT_ROOT / "crates/fp-conformance/oracle/pandas_oracle.py"
FIXTURE_ROOT = PROJECT_ROOT / "crates/fp-conformance/fixtures/packets"
PROVENANCE_KEY = "fixture_provenance"


def run_oracle(fixture: dict[str, Any], legacy_root: str, timeout: int) -> dict[str, Any]:
    """Drive the oracle exactly as the Rust harness does."""
    proc = subprocess.run(
        [
            sys.executable,
            str(ORACLE),
            "--legacy-root",
            legacy_root,
            "--allow-system-pandas-fallback",
        ],
        input=json.dumps(fixture).encode(),
        capture_output=True,
        timeout=timeout,
        check=False,
    )
    if not proc.stdout:
        raise RuntimeError(
            f"oracle produced no stdout (exit {proc.returncode}): "
            f"{proc.stderr.decode(errors='replace')[:300]}"
        )
    return json.loads(proc.stdout)


def compare(fixture: dict[str, Any], response: dict[str, Any]) -> tuple[list[str], dict[str, Any]]:
    """Return (changed expected keys, the updated fixture).

    Only keys already present in the fixture are considered or written.
    """
    changed: list[str] = []
    updated = json.loads(json.dumps(fixture))  # deep copy, order preserved
    for key in fixture:
        if not key.startswith("expected"):
            continue
        if key not in response:
            continue
        if response[key] != fixture[key]:
            changed.append(key)
            updated[key] = response[key]
    if PROVENANCE_KEY in response:
        updated[PROVENANCE_KEY] = response[PROVENANCE_KEY]
    return changed, updated


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--legacy-root", default="/nonexistent")
    parser.add_argument("--apply", action="store_true", help="write changes to disk")
    parser.add_argument(
        "--i-reviewed-the-diff",
        action="store_true",
        help="required alongside --apply; see AGENTS.md step 5",
    )
    parser.add_argument("--glob", default="*.json", help="restrict to matching fixtures")
    parser.add_argument("--limit", type=int, default=0, help="stop after N fixtures (0 = all)")
    parser.add_argument("--timeout", type=int, default=120)
    args = parser.parse_args()

    if args.apply and not args.i_reviewed_the_diff:
        print(
            "REFUSING to --apply without --i-reviewed-the-diff.\n"
            "p6srr: regenerating without reading the corpus diff is the "
            "golden-regeneration reflex at corpus scale.",
            file=sys.stderr,
        )
        return 2

    fixtures = sorted(FIXTURE_ROOT.glob(args.glob))
    if args.limit:
        fixtures = fixtures[: args.limit]
    if not fixtures:
        print(f"no fixtures matched {args.glob!r}", file=sys.stderr)
        return 2

    provenance_only = 0
    value_moved: list[tuple[str, list[str], str]] = []
    errored: list[tuple[str, str]] = []
    unchanged = 0
    by_prior_sha: collections.Counter[str] = collections.Counter()

    for path in fixtures:
        fixture = json.loads(path.read_text(encoding="utf-8"))
        prior = (fixture.get(PROVENANCE_KEY) or {}).get("oracle_script_sha256", "?")
        try:
            response = run_oracle(fixture, args.legacy_root, args.timeout)
        except Exception as exc:  # noqa: BLE001 - report and continue
            errored.append((path.name, str(exc)[:160]))
            continue
        if response.get("error"):
            errored.append((path.name, f"oracle error: {response['error']}"))
            continue

        changed, updated = compare(fixture, response)
        if changed:
            value_moved.append((path.name, changed, prior))
            by_prior_sha[prior[:16]] += 1
        elif updated.get(PROVENANCE_KEY) != fixture.get(PROVENANCE_KEY):
            provenance_only += 1
        else:
            unchanged += 1

        if args.apply:
            path.write_text(json.dumps(updated, indent=2) + "\n", encoding="utf-8")

    total = len(fixtures)
    print(f"fixtures examined      : {total}")
    print(f"  already current      : {unchanged}")
    print(f"  provenance-only stale: {provenance_only}")
    print(f"  VALUE MOVED          : {len(value_moved)}   <-- needs human review")
    print(f"  oracle errored       : {len(errored)}")
    if value_moved:
        print("\nVALUE MOVED, bucketed by the oracle generation that produced them:")
        for sha, count in by_prior_sha.most_common():
            print(f"  prior sha {sha}...  {count}")
        print("\nfirst 25:")
        for name, keys, prior in value_moved[:25]:
            print(f"  {name}: {', '.join(keys)}  (from {prior[:12]}...)")
    if errored:
        print("\nORACLE ERRORS (first 15):")
        for name, msg in errored[:15]:
            print(f"  {name}: {msg}")
    if not args.apply:
        print("\nDRY RUN — nothing written. Re-run with --apply --i-reviewed-the-diff.")
    return 1 if errored else 0


if __name__ == "__main__":
    sys.exit(main())
